/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chess;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
    @Test
    void appHasAGreeting() {
        App application = new App();
        assertNotNull(application.getGreeting(), "app should have a greeting");
    }

}
