/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chess;


import javax.swing.*;
import java.awt.*;

public class Application extends JFrame {


    public Application() {
        this.setTitle("Chess");

        this.setMinimumSize(new Dimension(PositionRectangle.BOARD_SIZE, PositionRectangle.BOARD_SIZE));
        this.setSize(800, 825);

        this.add(new GridUI());

        this.setResizable(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            Application chessApp = new Application();
            chessApp.setVisible(true);
        });
    }
}