/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chess;


import javax.swing.*;

public class Application extends JFrame {

    private final BoardUI board = new BoardUI();

    public Application() {
        this.add(this.board);
        this.setTitle("Chess");
        this.setSize(800, 800);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            Application chessApp = new Application();
            chessApp.setVisible(true);
        });
    }
}