/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chessboard;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App application = new App();
        assertNotNull(application.getGreeting(), "app should have a greeting");
    }

    @Test void shouldFail() {
        App classUnderTest = new App();
        assertNull(classUnderTest.getGreeting(), "app should say Hello World!");
    }
}
