on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version-file: ./java-version
          cache: gradle

      - uses: gradle/gradle-build-action@v2

      - run: ./gradlew build --no-daemon

      - run: ./gradlew test --no-daemon

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/libs
